export const SALE_AUDIT_ACTIONS = {
  SALE_CONFIRMED: 'SALE_CONFIRMED',
  DEBT_PAYMENT: 'SALE_DEBT_PAYMENT',
  SALE_CANCELLED: 'SALE_CANCELLED',
  SALE_DATE_UPDATED: 'SALE_DATE_UPDATED',
  SALE_ITEM_PRICE_UPDATED: 'SALE_ITEM_PRICE_UPDATED',
} as const;
