export const RECEIPT_AUDIT_ACTIONS = {
  RECEIPT_CREATED: 'RECEIPT_CREATED',
  RECEIPT_UPDATED: 'RECEIPT_UPDATED',
  RECEIPT_CALCULATED: 'RECEIPT_CALCULATED',
  RECEIPT_COMPLETED: 'RECEIPT_COMPLETED',
  RECEIPT_CANCELLED: 'RECEIPT_CANCELLED',
  RECEIPT_ITEM_RECEIVED: 'RECEIPT_ITEM_RECEIVED',
} as const;

export type ReceiptAuditAction =
  (typeof RECEIPT_AUDIT_ACTIONS)[keyof typeof RECEIPT_AUDIT_ACTIONS];
